bookers2/config/routes.rb
Rails.application.routes.draw do

  get 'chats/show'
  get 'search/search'
  get 'users/show'
  devise_for :users, :controllers => {
    :confirmations => 'users/confirmations',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'books#top'

  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    #resource :otherfavorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  #resources :relationships, only: [:create, :destroy]
  post 'relationships/:id' => 'relationships#create', as: 'follow'
  get 'relationships/follower' => 'relationships#index', as: 'follower'
  get 'relationships/followed' => 'relationships#index2', as: 'followed'
  delete 'relationships/:id' => 'relationships#destroy', as: 'unfollow'

  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]



end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 

  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }
end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true 
end

bookers2/app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

bookers2/app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :followed_user, through: :followed, source: :follower
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms


  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum:50 }
  validates :name, uniqueness: true

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
  
  include JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end 
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  
end

bookers2/app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]='Book was successfully created.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]='Book was successfully updated.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :edit
    end
  end

  def index
    @book_new = Book.new
    @book = Book.new
    @books = Book.all
    @book_comment = BookComment.new
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.all
    @book_comment = BookComment.new
    #@book_comment = @book.book_comment
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.permit(:name, :profile_image, :introduction)
  end

end

bookers2/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    
    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end 
  
  private
  
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
  
end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def show
    #@book = Book.new
    #@book = Book.find(params[:id])
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book_new = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]='Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
    @book_new = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]='User_profile was successfully updated.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/chats_helper.rb
module ChatsHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/search_helper.rb
module SearchHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <header>

      <% if user_signed_in? %>
        <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
          <div class='container'>
            <p class='navbar-brand'><%= link_to 'Bookers', root_path, class:'text-light' %></p>

            <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expandef='true' aria-label='Toggle navigation'></button>

            <div class='navbar-collapse collapse show' id='navbarNavDropdown' >
              <ul class='navbar-nav ml-auto'>
                <li class='fas nav-link'>
                  <%= link_to user_path(current_user.id), class:'text-light' do %>
                    <text class='fas fa-home'></text>
                    Home
                  <% end %>
                </li>
                <li class='fas nav-link'>
                  <%= link_to users_path, class:'text-light' do %>
                    <text class='fas fa-users'></text>
                    Users
                  <% end %>
                </li>
                <li class='fas nav-link'>
                  <%= link_to books_path, class:'text-light' do %>
                    <text class='fas fa-book-open'></text>
                    Books
                  <% end %>
                </li>
                <li class='fas nav-link'>
                  <%= link_to destroy_user_session_path, method: :delete, class:'text-light' do  %>
                    <text class='fas fa-sign-out-alt'></text>
                    logout
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>

      <% else %>
        <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
          <div class='container'>
            <p class='navbar-brand'><%= link_to 'Bookers', root_path %></p>

            <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expandef='true' aria-label='Toggle navigation'></button>

            <div class='navbar-collapse collapse show' id='navbarNavDropdown' >
              <ul class='havbar-nav ml-auto'>
                <li class='fas nav-link'>
                  <%= link_to root_path, class:'text-light' do %>
                    <text class='fas fa-home'></text>
                    Home
                  <% end %>
                </li>
                <li class='fas nav-link'>
                  <%= link_to home_about_path, class:'text-light' do %>
                    <text class='fas fa-link'></text>
                    About
                  <% end %>
                </li>
                <li class='fas nav-link'>
                  <%= link_to new_user_registration_path, class:'text-light' do %>
                    <text class='fas fa-user-plus'></text>
                    Sign up
                  <% end %>
                </li>
                <li class='fas nav-link'>
                  <%= link_to new_user_session_path, class:'text-light' do  %>
                    <text class='fas fa-sign-in-alt'></text>
                    login
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      <% end %>

      <div class='container'>
        <div class='row'>
          <div class='mx-auto'>
            <% if user_signed_in? %>
              <%= form_with url:search_path, method: :get, local: true do |f| %>
                <%= f.text_field 'search[value]' %>
                <%= f.select 'search[model]', options_for_select({'User' => 'user', 'Book' => 'book'}) %>
                <%= f.select 'search[how]', options_for_select({'完全一致' => 'match', '前方一致' => 'forward', '後方一致' => 'backward', '部分一致' => 'partical'}) %>
                <%= f.submit :'検索' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

  </header>

  <body>
    <%= yield %>
  </body>

  <footer>
    <div class='container mt-5'>
      <div class='row'>
        <div class='mx-auto'>
          CopyRight infratop.inc
        </div>
      </div>
    </div>
  </footer>
</html>