bookers2/config/routes.rb
Rails.application.routes.draw do

  get 'chats/show'
  get 'search/search'
  get 'users/show'
  devise_for :users, :controllers => {
    :confirmations => 'users/confirmations',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'books#top'

  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    #resource :otherfavorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  #resources :relationships, only: [:create, :destroy]
  post 'relationships/:id' => 'relationships#create', as: 'follow'
  get 'relationships/follower' => 'relationships#index', as: 'follower'
  get 'relationships/followed' => 'relationships#index2', as: 'followed'
  delete 'relationships/:id' => 'relationships#destroy', as: 'unfollow'

  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]



end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 

  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]='Book was successfully created.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]='Book was successfully updated.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :edit
    end
  end

  def index
    @book_new = Book.new
    @book = Book.new
    @books = Book.all
    @book_comment = BookComment.new
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.all
    @book_comment = BookComment.new
    #@book_comment = @book.book_comment
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.permit(:name, :profile_image, :introduction)
  end

end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
<div>
  <span>
    <%= link_to user_path(book_comment.user_id) do %>
      <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:'no_image.jpg') %>
      <br><%= book_comment.user.name %>
    <% end %>
  </span>
  <span><%= book_comment.comment %></span>
  <span><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), class:'btn btn-sm btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %> </span>
</div>
<% end %>

bookers2/app/views/books/_favorite.html.erb
  <% if book.favorited_by?(current_user) %>
    <th>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
        <text class='text-danger'>♥<%= book.favorites.count %></text>
      <% end %>
    </th>
  <% else %>
    <th>
      <%= link_to book_favorites_path(book.id), method: :post do %>
        ♡<%= book.favorites.count %>
      <% end %>
    </th>
  <% end %>

bookers2/app/views/books/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format:'jpeg', fallback:'no_image.jpg' %>

<table class='table'>
    <tbody>
        <tr>
            <th>name</th>
            <th><%= user.name %></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
        </tr>
        <tr>
            <th>follows</th>
            <th><%= link_to user.follower.count, follower_path(user_id: user.id) %></th>
        </tr>
        <tr>
            <th>followers</th>
            <th><%= link_to user.followed.count, followed_path(user_id: user.id) %></th>
        </tr>
    </tbody>
</table>
<% unless user == current_user %>
    <div class='row'>
        <% if current_user.following?(user) %>
            <%= link_to 'フォロー外す', unfollow_path(user.id), method: :delete, class:'btn btn-sm btn-info' %>
        <% else %>
            <%= link_to 'フォローする', follow_path(user.id), method: :post, class:'btn btn-sm btn-success' %>
        <% end %>
    </div>
<% end %>

<% if current_user != user %>
    <%= link_to 'chatを始める', chat_path(user.id) %>
<% end %>

<% if user == current_user %>
    <div class='row'>
        <%= link_to edit_user_path(user), class:'btn btn-outline-secondary btn-block fas fa-user-cog' do %>
        <% end %>
    </div>
<% end %>

bookers2/app/views/books/_newbook.html.erb
                <div>
                    <h2 class='mt-3'>New book</h2>
                    <%= form_with model:book, local:true do |f| %>
                        <div class='form-group'>
                            <p for='inputTitle'>Title</p>
                            <%= f.text_field :title, autofocus:true, id:'inputTitle' %>
                        </div>
                        <div class='form-group'>
                            <p for='inputOpinion'>Opinion</p>
                            <%= f.text_field :body, autofocus:true, id:'inputOpinion' %>
                        </div>
                        <div class='form-group'>
                            <%= f.submit 'Create Book', class:'btn btn-success' %>
                        </div>
                    <% end %>
                </div>

bookers2/app/views/books/edit.html.erb
<main>
   <% if @book.errors.any? %>
    <div class='errorframe'>
        <h2>error...</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='container'>
    <div class='row'>
      <div class='col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto'>
        <h1>Editing Book</h1>

          <%= form_with model:@book, local:true do |f| %>
            <div class='form-group'>
              <p for='inputTitle'>Title</p>
              <%= f.text_field :title, autofocus:true, id:'inputTitle' %>
            </div>
            <div class='form-group'>
              <p for='inputOpinion'>Opinion</p>
              <%= f.text_field :body, autofocus:true, id:'inputOpinion' %>
            </div>
            <div class='form-group'>
              <%= f.submit 'Update Book', class:'btn btn-success' %>
            </div>
          <% end %>
          <%= link_to 'Show', book_path(@book) %>
          <text>|</text>
          <%= link_to 'Back', books_path %>

      </div>
    </div>
  </div>

</main>

bookers2/app/views/books/index.html.erb
<main>

    <% if flash[:notice] %>
      <p class='notice'><%= flash[:notice]%></p>
    <% end %>

    <% if @book.errors.any? %>
      <div class='errorframe'>
         <h2>error...</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='container px-5 px-5m0'>
        <div class='row'>
            <div class='col-md-3'>
                <%= render 'books/info', user: current_user %>
                <%= render 'books/newbook', book: @book_new %>
            </div>

            <div class='col-md-8 offset-md-1'>
                <h2>Books</h2>
                <table class='table table-hover table-inverse'>
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspan='6'></th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @books.each do |book| %>
                            <tr>
                                <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:'no_image.jpg'), user_path(book.user_id) %></td>
                                <td><%= link_to book.title, book_path(book) %></td>
                                <td><%= book.body %></td>
                                <td id='fav_index_<%= book.id %>' >
                                   <%= render 'favorites/favorite', book: book %>
                                </td>
                                <td>
                                    <th>コメント数: <%= book.book_comments.count %></th>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</main>

bookers2/app/views/books/show.html.erb
<main>
    <% if flash[:notice] %>
      <p class='notice'><%= flash[:notice]%></p>
    <% end %>
    <div class='container px-5 px-5m0'>
        <div class='row'>
            <div class='col-md-3'>
                <%= render 'books/info', user: @user %>
                <%= render 'books/newbook', book: @book_new %>
            </div>

            <div class='col-md-8 offset-md-1'>
                <h2>Book detail</h2>
                <table class='table table-hover table-inverse'>
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspan='6'></th>
                        </tr>
                    </thead>

                    <tbody>
                            <tr>
                                <td>
                                    <a href='/users/<%= @user.id %>'>
                                        <img class='attachment user profile_image fallback'><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format:'jpeg', fallback:'no_image.jpg' %><br>
                                            <%= @user.name %>
                                        </img>
                                    </a>
                                </td>
                                <td>
                                    <%= link_to @book.title, book_path(@book) %>
                                </td>

                                <td><%= @book.body %></td>
                                <% if @book.user == current_user %>
                                    <td>
                                        <%= link_to 'Edit', edit_book_path(@book), class:'btn btn-sm btn-success' %>
                                    </td>
                                    <td>
                                        <%= link_to 'Destroy', book_path(@book), class:'btn btn-sm btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
                                    </td>
                                <% end %>

                                <td class='favorite'>
                                    <%= render 'favorites/favorite', book: @book %>
                                </td>
                                <td>
                                    <th>コメント数: <%= @book.book_comments.count %></th>
                                </td>
                            </tr>
                    </tbody>
                </table>

                <div class='comment'>
                    <%= render 'book_comments/comment', book: @book %>
                </div>
                <div>
                    <%= form_with(model:[@book, @book_comment]) do |f| %>
                    <div class='field' >
                        <%= f.text_area :comment, rows:'5', cols:'40' %>
                    </div>
                    <div class='action'>
                        <%= f.submit '送信' %>
                    </div>
                    <% end %>
                </div>

            </div>
        </div>
    </div>
</main>

bookers2/app/views/books/top.html.erb
<main>
  <% if flash[:notice] %>
      <p class='notice'><%= flash[:notice]%></p>
  <% end %>
  <div class='container'>
    <div class='row'>
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>Welcome to <i class='fas fa-book'></i><strong>Bookers!!</strong></h1>
        <p>in<i class='fas fa-book'></i><strong> Bookers,</strong></p>
        <p>you can share and exchange your opinions, impressions, and emotions</p>
        <p>about various books!</p>
      
        <div class='btn-wrapper col-10 mx-auto'>
          <div class='row'>
            <a class='btn btn-info btn-sm btn-block mb-3', href='/users/sign_in'>Log In</a>
          </div>
          <div class='row'>
            <a class='btn btn-success btn-sm btn-block mb-3', href='/users/sign_up'>Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>